# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    id: controller
    main: ./cmd/controller
    binary: controller
    ldflags:
      - -s -w
      - -X github.com/senthilrch/kube-fledged/pkg/version.version={{ .Version }}
      - -X github.com/senthilrch/kube-fledged/pkg/version.buildDate={{ .Date }}
      - -X github.com/senthilrch/kube-fledged/pkg/version.gitCommit={{ .Commit }}
      - -X github.com/senthilrch/kube-fledged/pkg/version.gitTreeState=clean
      - -X github.com/senthilrch/kube-fledged/pkg/version.gitTag={{ .Tag }}
archives:
  - id: controller
    format: binary
    builds:
      - controller
    name_template: >-
      {{ .Binary }}_{{ .Version }}_{{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^build:'
      - '^ci:'
      - '^docs:'
      - '^test:'
      - '^chore:'
dockers:
- image_templates:
  - "modelzai/kube-fledged-controller:v{{ .Version }}-amd64"
  use: buildx
  dockerfile: Dockerfile
  ids:
  - controller
  build_flag_templates:
  - "--platform=linux/amd64"
docker_manifests:
- name_template: modelzai/kube-fledged-controller:v{{ .Version }}
  image_templates:
  - modelzai/kube-fledged-controller:v{{ .Version }}-amd64
